### ISSUE TITLE
Issue with the latest React 15.1.0

### ISSUE THREAD

**Issue by ShotaMegre** [sanniassin/react-input-mask#46]
It was working fine with React 0.14.7, though it throws warning with React 15.1.0 when trying to change mask of the InputElement.
Code to reproduce:
`<InputElement id="myid" className="myclass" name="myname" type="text" mask={this.state.mask} maskChar="_" />`

Warning message:
InputElement is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

**Comment by sanniassin** [comment]
@ShotaMegre Can't reproduce. Can you make a minimal project which fail?

**Comment by sanniassin** [comment]
@ShotaMegre I suppose it should be fixed with this commit https://github.com/sanniassin/react-input-mask/commit/2897994e463faf26525a9f764922d375703383d6. Please check it with current master branch

**Comment by ShotaMegre** [comment]
The issue is still valid.
Requiring by the following doesn't work:
var InputElement = require('react-input-mask/InputElement');
(bundling crashes).

While requiring the build version still throws the same warning:
var InputElement = require('react-input-mask/build/InputElement');

**Comment by sanniassin** [comment]
@ShotaMegre You need to build it first with ```npm install && npm run build```

**Comment by ShotaMegre** [comment]
Sure, I'm building it first. And if I include InputElement by requiring it through:
var InputElement = require('react-input-mask/InputElement'); 
Then the build crashes.
![image](https://cloud.githubusercontent.com/assets/16485865/16142080/78d68366-3473-11e6-97bb-3ae83dc47009.png)
I'm using:
var InputElement = require('react-input-mask**/build/**InputElement');
And I've warning message in Chrome console as given above when I try to set the mask of the input element.

**Comment by sanniassin** [comment]
@ShotaMegre Back to minimal project then. Or you can try to fork this pen and modify it to reproduce warning (this pen has warning with 0.6.9 and works fine now with master) – http://codepen.io/sanniassin/pen/LpvMyx

**Comment by ShotaMegre** [comment]
Check this:
http://codepen.io/ShotaMegre/pen/oLLRoz
The main part of the code is taken from **build**/InputElement.js

**Comment by sanniassin** [comment]
@ShotaMegre For some reason your build is not a latest one. Try this one (it's a **build** version which you can use with ```require```)
[InputElement.zip](https://github.com/sanniassin/react-input-mask/files/320275/InputElement.zip)

**Comment by ShotaMegre** [comment]
The file in the archive from your message works perfectly.
Please replace the InputElement in build directory of your project with this one, as if I even remove and reinstall your package, it comes with the code that is buggy.

**Comment by sanniassin** [comment]
Updated to 0.7.0 at npm. Enjoy :)
