### ISSUE TITLE
Copy/paste issue

### ISSUE THREAD

**Issue by reintroducing** [sanniassin/react-input-mask#7]
Hello and thank you for this fantastic component.  I'm running into an issue where I copy paste a CC number and I see an error in the console.  My mask settings are:

```
mask="9999 9999 9999 9999"
maskChar={null}
```

If you copy paste the following: 

```
4242 4242 4242 4242
``` 

you will see the issue in the console:

InputElement.js:517 Uncaught ReferenceError: i is not defined

Please let me know what I can do to help on this and if you need me to build an example out.

Again, thanks for the wonderful class. It's just about the only input masking utility I've found that acts as I fully expect it to.  It actually ended up being the reason why I implemented Babel and React in our code base just yesterday. It was the perfect excuse to start using them and now we're off to the races :)

**Comment by sanniassin** [comment]
At first thank you for warm feedback :)

This issue fixed in https://github.com/sanniassin/react-input-mask/commit/05c898be6860d210dc906374e4cb0f71b0c997e9 (or version 0.1.4 at npm).

Also i decided to replace chars instead of shift in fully filled input with null maskChar in version 0.2.0 which is latest at this moment.

**Comment by reintroducing** [comment]
Thanks, that fixes the issue. However, lets say I want to copy an American Express number over a Visa number (amex has only 15 numbers). Try pasting this over my prior CC number:

```
3782 822463 10005
```

Now you will see that a 2 from the old credit card number is left after the 5 in the new one. I think the expected behavior would be that all numbers would be deleted and the new one pasted thus leaving only 15 characters in the field, not 16.  What do you think?

**Comment by sanniassin** [comment]
Yep, on-the-fly mask changes was broken, thank you. Fixed in 0.2.1

For future bugs it's better to open own issue for each bug.

**Comment by reintroducing** [comment]
Sorry about that, I moved this into a separate issue as I'm still experiencing it in 0.2.1.

**Comment by wtusfo** [comment]
hi my mask is mask='+63(\999) 999-99-99' and maskChar is maskChar='X' ,  when i try to paste number like 99 999 99 9(even without empty spaces) mask puts 639 after +639 one more time. Can anyone help me with this ?
